version: '3.9'

services:
  backend:
    restart: always
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 3002:3002
    volumes:
      - ./backend:/app
      - /app/node_modules

  frontend:
    restart: always
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/app
      - /app/node_modules

  bff:
    restart: always
    build:
      context: ./bff
      dockerfile: Dockerfile
    ports:
      - 3001:3001
    volumes:
      - ./bff:/app
      - /app/node_modules

  redis:
    image: bitnami/redis
    ports:
      - '6379:6379'
    restart: always
    environment:
      - REDIS_PASS=redis
    command: |
      bash -euxc "redis-server --requirepass $$REDIS_PASS"
  rabbitmq:
    image: bitnami/rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    restart: always
    environment:
      # 로컬 큐 서버는 환경변수 관리 안함
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=password
  mariadb:
    image: bitnami/mariadb
    restart: always
    ports:
      - 3306:3306
    environment:
      MARIADB_ROOT_PASSWORD: example
